
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luck
 */
public class Checkbox extends javax.swing.JFrame {

    /**
     * Creates new form Checkbox
     */
    public Checkbox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pogrubiony = new javax.swing.JCheckBox();
        pochylony = new javax.swing.JCheckBox();
        etykieta = new javax.swing.JLabel();
        font_1 = new javax.swing.JCheckBox();
        font_2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pogrubiony.setText("pogrubiony");
        pogrubiony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pogrubionyActionPerformed(evt);
            }
        });

        pochylony.setText("pochylony");
        pochylony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pochylonyActionPerformed(evt);
            }
        });

        etykieta.setText("To jest tekst do prób");

        font_1.setText("Font_1");
        font_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                font_1ActionPerformed(evt);
            }
        });

        font_2.setText("Font_2");
        font_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                font_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(pogrubiony)
                        .addGap(18, 18, 18)
                        .addComponent(pochylony)
                        .addGap(18, 18, 18)
                        .addComponent(font_1)
                        .addGap(18, 18, 18)
                        .addComponent(font_2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(etykieta)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pogrubiony)
                    .addComponent(pochylony)
                    .addComponent(font_1)
                    .addComponent(font_2))
                .addGap(18, 18, 18)
                .addComponent(etykieta)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pogrubionyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pogrubionyActionPerformed
       setStyle();
    }//GEN-LAST:event_pogrubionyActionPerformed

    private void pochylonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pochylonyActionPerformed
       setStyle();
    }//GEN-LAST:event_pochylonyActionPerformed

    private void font_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_font_1ActionPerformed
        setStyle();
    }//GEN-LAST:event_font_1ActionPerformed

    private void font_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_font_2ActionPerformed
      setStyle();
    }//GEN-LAST:event_font_2ActionPerformed

    private void setStyle()
    {
        String a = "Monospaced";
        String b = "Courier new";
        
        int style = Font.PLAIN;
        if(pochylony.isSelected())
        {
         style += Font.ITALIC;    
        }
        if(pogrubiony.isSelected())
        {
         style += Font.BOLD;
        }
        if(font_1.isSelected())
        {
             etykieta.setFont(new Font(a, style, 25));
        }
        if(font_2.isSelected())
        {
            etykieta.setFont(new Font(b, style, 25));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkbox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etykieta;
    private javax.swing.JCheckBox font_1;
    private javax.swing.JCheckBox font_2;
    private javax.swing.JCheckBox pochylony;
    private javax.swing.JCheckBox pogrubiony;
    // End of variables declaration//GEN-END:variables
}
